CREATE DATABASE FACTURACION
GO
USE FACTURACION
GO

CREATE TABLE ARTICLES(
	ID_ARTICLE INT IDENTITY(1,1),
	NAME VARCHAR(100),
	UNIT_PRICE DECIMAL(10,2)
	CONSTRAINT PK_ARTICLES PRIMARY KEY (ID_ARTICLE)
);

CREATE TABLE PAYMENT_TYPES(
	ID_PAYMENT_TYPE INT,
	NAME VARCHAR(100),
	CONSTRAINT PK_PAYMENT_TYPES PRIMARY KEY(ID_PAYMENT_TYPE)
);

CREATE TABLE INVOICES(
	ID_INVOICE INT IDENTITY(1,1),
	DATE_REGISTER DATE,
	ID_PAYMENT_TYPE INT,
	CLIENT VARCHAR(100),
	CONSTRAINT PK_ID_INVOICE PRIMARY KEY (ID_INVOICE),
	CONSTRAINT PK_ID_INVOICE_PAYMENT_TYPE FOREIGN KEY (ID_PAYMENT_TYPE)
		REFERENCES PAYMENT_TYPES(ID_PAYMENT_TYPE)
);

CREATE TABLE INVOICE_DETAILS(
	ID_INVOICE_DETAIL INT,
	ID_INVOICE INT,
	ID_ARTICLE INT,
	AMOUNT INT,
	CONSTRAINT PK_INVOICE_DETAILS PRIMARY KEY (ID_INVOICE_DETAIL,ID_INVOICE),
	CONSTRAINT FK_INVOICE_DETAILS_INVOICE FOREIGN KEY (ID_INVOICE)
		REFERENCES INVOICES(ID_INVOICE),
	CONSTRAINT FK_INVOICE_DETAILS_ARTICLES FOREIGN KEY (ID_ARTICLE)
		REFERENCES ARTICLES(ID_ARTICLE)
);
GO
CREATE PROCEDURE SP_GET_ALL_ARTICLES
AS
	BEGIN
		SELECT ID_ARTICLE,NAME,UNIT_PRICE
		FROM ARTICLES
	END
GO
CREATE PROCEDURE SP_ADD_ARTICLE
@NAME VARCHAR(100),
@UNIT_PRICE DECIMAL(10,2)
AS
	BEGIN
		INSERT INTO ARTICLES (NAME,UNIT_PRICE)
			VALUES (@NAME,@UNIT_PRICE);
	END
GO
CREATE PROCEDURE SP_DELETE_ARTICLE
@ID_ARTICLE INT
AS
	BEGIN
		DELETE FROM ARTICLES
		WHERE ID_ARTICLE = @ID_ARTICLE
	END
GO
CREATE PROCEDURE SP_UPDATE_ARTICLE
@ID_ARTICLE INT,
@NAME VARCHAR(100),
@UNIT_PRICE DECIMAL(10,2)
AS
	BEGIN
		UPDATE ARTICLES
			SET NAME = @NAME,
				UNIT_PRICE = @UNIT_PRICE
			WHERE ID_ARTICLE = @ID_ARTICLE
	END
GO
CREATE PROCEDURE SP_GET_ALL_PAYMENT_TYPES
AS 
	BEGIN
		SELECT ID_PAYMENT_TYPE,NAME
		FROM PAYMENT_TYPES
	END
GO

CREATE PROCEDURE SP_ADD_PAYMENT_TYPE
@ID INT,
@NAME VARCHAR(100)
AS
	BEGIN
		INSERT INTO PAYMENT_TYPES(ID_PAYMENT_TYPE,NAME)
			VALUES(@ID,@NAME);
	END
GO
CREATE PROCEDURE SP_ADD_INVOICE
@DATE DATE,
@ID_PAYMENT_TYPE INT,
@CLIENT VARCHAR(100),
@ID_INVOICE INT OUTPUT
AS
	BEGIN
		INSERT INTO INVOICES (DATE_REGISTER,ID_PAYMENT_TYPE,CLIENT)
			VALUES (@DATE,@ID_PAYMENT_TYPE,@CLIENT);
		SET @ID_INVOICE = SCOPE_IDENTITY();
	END

GO
CREATE PROCEDURE SP_ADD_INVOICE_DETAILS
@ID_INVOICE INT,
@ID_INVOICE_DETAIL INT,
@ID_ARTICLE INT,
@AMOUNT INT
AS
	BEGIN
		INSERT INTO INVOICE_DETAILS(ID_INVOICE,ID_INVOICE_DETAIL,ID_ARTICLE,AMOUNT)
			VALUES (@ID_INVOICE,@ID_INVOICE_DETAIL,@ID_ARTICLE,@AMOUNT);
	END
GO
CREATE PROCEDURE SP_UPDATE_INVOICE

@DATE DATE,
@ID_PAYMENT_TYPE INT,
@CLIENT VARCHAR(100),
@ID_INVOICE INT
AS
	BEGIN
		UPDATE INVOICES
			SET DATE_REGISTER = @DATE,
				ID_PAYMENT_TYPE = @ID_PAYMENT_TYPE,
				CLIENT = @CLIENT
			WHERE ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_UPDATE_INVOICE_DETAIL
@ID_INVOICE INT,
@ID_INVOICE_DETAIL INT,
@ID_ARTICLE INT,
@AMOUNT INT
AS
	BEGIN
		UPDATE INVOICE_DETAILS
			SET ID_ARTICLE = @ID_ARTICLE,
				AMOUNT = @AMOUNT
			WHERE ID_INVOICE_DETAIL = @ID_INVOICE AND ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_GET_ALL_INVOICES
AS
	BEGIN
		SELECT ID_INVOICE, DATE_REGISTER, ID_PAYMENT_TYPE, CLIENT
		FROM INVOICES
	END
GO
CREATE PROCEDURE SP_GET_INVOICE_BY_ID
@ID_INVOICE INT
AS 
	BEGIN
		SELECT ID_INVOICE, DATE_REGISTER, ID_PAYMENT_TYPE, CLIENT
		FROM INVOICES WHERE ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_DELETE_INVOICE_DETAIL
@ID_INVOICE INT
AS
	BEGIN
		DELETE FROM INVOICE_DETAILS
		WHERE ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_DELETE_INVOICE
@ID_INVOICE INT
AS
	BEGIN
	DELETE FROM INVOICES
	WHERE ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_GET_ALL_INVOICE_DETAILS
AS
	BEGIN
		SELECT ID_INVOICE_DETAIL, ID_INVOICE, ID_ARTICLE, AMOUNT
		FROM INVOICE_DETAILS
	END
GO
CREATE PROCEDURE SP_GET_DETAIL_BY_ID
@ID_INVOICE INT
AS
	BEGIN 
		SELECT ID_INVOICE_DETAIL, ID_INVOICE, ID_ARTICLE, AMOUNT
		FROM INVOICE_DETAILS WHERE ID_INVOICE = @ID_INVOICE
	END
GO
CREATE PROCEDURE SP_GET_ARTICLE_BY_ID
@ID_ARTICLE INT
AS
	BEGIN
		SELECT ID_ARTICLE, NAME, UNIT_PRICE
		FROM ARTICLES
	END
GO
CREATE PROCEDURE SP_GET_INVOICE_BY_FILTERS
@DATE DATE = '01/01/2000',
@PAYMENT_TYPE INT = 1
AS
	BEGIN
		SELECT ID_INVOICE, DATE_REGISTER, ID_PAYMENT_TYPE, CLIENT
		FROM INVOICES
		WHERE DATE_REGISTER >= @DATE
		AND ID_PAYMENT_TYPE = @PAYMENT_TYPE
	END
GO
INSERT INTO PAYMENT_TYPES (ID_PAYMENT_TYPE,NAME)
	VALUES (1,'Tarjeta de Credito'),
		   (2,'Tarjeta de Debito');